/*
 * Created on 2022-11-27 ( 09:03:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.student.demo.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Students"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="students", schema="public" )
public class Students implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="register_number", nullable=false)
    private Integer    registerNumber ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", length=50)
    private String     name ;

    @Temporal(TemporalType.DATE)
    @GeneratedValue(strategy=GenerationType.SEQUENCE)
    @Column(name="dob")
    private Date       dob ;

    @Column(name="phone_number", length=10)
    private String     phoneNumber ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     * @param phonenumber2 
     * @param registerNumber2 
     * @param name2 
     * @param phonenumber2 
     * @param dob2 
     * @param name2 
     */
    public Students() {
	
    }
    
    


//	public Students(String name2, Date dob2, String phonenumber2) {
//		// TODO Auto-generated constructor stub
//	}


	public Students(String name, int registerNumber, String phoneNumber) {
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.registerNumber=registerNumber;
	}


	//--- GETTERS & SETTERS FOR FIELDS
    public void setRegisterNumber( Integer registerNumber ) {
        this.registerNumber = registerNumber ;
    }
    public Integer getRegisterNumber() {
        return this.registerNumber;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDob( Date dob ) {
        this.dob = dob ;
    }
    public Date getDob() {
        return this.dob;
    }

    public void setPhoneNumber( String phoneNumber ) {
        this.phoneNumber = phoneNumber ;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(registerNumber);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(dob);
        sb.append("|");
        sb.append(phoneNumber);
        return sb.toString(); 
    } 

}
